# Script which sets all of the GPIO pins on the RPi high

from time import sleep
import RPi.GPIO as GPIO
GPIO.setmode(GPIO.BCM)
GPIO.setup(1, GPIO.OUT)
GPIO.setup(2, GPIO.OUT)
GPIO.setup(3, GPIO.OUT)
GPIO.setup(4, GPIO.OUT)
GPIO.setup(5, GPIO.OUT)
GPIO.setup(6, GPIO.OUT)
GPIO.setup(7, GPIO.OUT)
GPIO.setup(8, GPIO.OUT)
GPIO.setup(9, GPIO.OUT)
GPIO.setup(10, GPIO.OUT)
GPIO.setup(11, GPIO.OUT)
GPIO.setup(12, GPIO.OUT)
GPIO.setup(13, GPIO.OUT)
GPIO.setup(14, GPIO.OUT)
GPIO.setup(15, GPIO.OUT)
GPIO.setup(16, GPIO.OUT)
GPIO.setup(17, GPIO.OUT)
GPIO.setup(18, GPIO.OUT)
GPIO.setup(19, GPIO.OUT)
GPIO.setup(20, GPIO.OUT)
GPIO.setup(21, GPIO.OUT)
GPIO.setup(22, GPIO.OUT)
GPIO.setup(23, GPIO.OUT)
GPIO.setup(24, GPIO.OUT)
GPIO.setup(25, GPIO.OUT)
GPIO.setup(26, GPIO.OUT)

while 1:
    GPIO.output(1, True)
    GPIO.output(2, True)
    GPIO.output(3, True)
    GPIO.output(4, True)
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(7, True)
    GPIO.output(8, True)
    GPIO.output(9, True)
    GPIO.output(10, True)
    GPIO.output(11, True)
    GPIO.output(12, True)
    GPIO.output(13, True)
    GPIO.output(14, True)
    GPIO.output(15, True)
    GPIO.output(16, True)
    GPIO.output(17, True)
    GPIO.output(18, True)
    GPIO.output(19, True)
    GPIO.output(20, True)
    GPIO.output(21, True)
    GPIO.output(22, True)
    GPIO.output(23, True)
    GPIO.output(24, True)
    GPIO.output(25, True)
    GPIO.output(26, True)
 
	 

